# Generated by Django 5.0 on 2023-12-12 20:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='note',
            name='date',
        ),
        migrations.AlterField(
            model_name='chel',
            name='password',
            field=models.TextField(),
        ),
    ]
